In [2]:
import numpy as np

In [3]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [4]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [5]:
# no hidden layer weights
weights = 2* np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[-0.09513203],
        [-0.22220105]]), array([-0.35043195]))

In [6]:
# forward propagation without any hidden layer
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[ 0.41327768],
       [ 0.3606295 ],
       [ 0.39041599],
       [ 0.33899747]])

In [7]:
# one hidden layer weights
wh = 2* np.random.random((2, 2)) - 1
bh = 2* np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1,1)) - 1

In [8]:
# forward propagation with one hidden layer
output0 = X
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden, wo) + bo)
output

array([[ 0.79308729],
       [ 0.80420825],
       [ 0.77241718],
       [ 0.78202028]])