In [1]:
import numpy as np

In [3]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [4]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [11]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [12]:
# no hidden layer weights
weights = 2* np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[-0.00894932],
        [-0.20218725]]), array([ 0.89805607]))

In [13]:
# forward propagation without any hidden layer
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[ 0.71054986],
       [ 0.6672712 ],
       [ 0.7087058 ],
       [ 0.6652813 ]])

In [17]:
# one hidden layer weights
wh = 2* np.random.random((2, 2)) - 1
bh = 2* np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1,1)) - 1
lr = 0.1

In [18]:
# nn for no hidden layer
'''
for iter in range(10000):
    output0 = X
    output = sig(np.dot(output0, weights) + bias)

    first_term = output - Y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term
    first_two.shape

    changes = np.dot(output0.T, first_two)
    weights = weights - lr*changes
    bias_change = np.sum(first_two)
    bias = bias - lr * bias_change
output = sig(np.dot(X, weights) + bias)
weights, bias, output
'''

(array([[ 5.47101775],
        [ 5.47101775]]), array([-8.29925618]), array([[  2.48639910e-04],
        [  5.58171628e-02],
        [  5.58171629e-02],
        [  9.33564551e-01]]))

In [20]:
# forward propagation with one hidden layer
for iter in range(10000):
        output0 = X
        inputHidden = np.dot(output0,wh)+bh
        outputHidden = sig(inputHidden) 
        inputforOutputLayer = np.dot(outputHidden,wo)+bo
        output = sig(np.dot(outputHidden, wo) + bo)
        first_term_for_output_layer = output-Y
        second_term_for_output_layer = derivativeSig(inputforOutputLayer)
        first_two_output_layer = first_term_for_output_layer*second_term_for_output_layer

        first_term_hidden_layer = np.dot(first_two_output_layer,wo.T)
        second_term_hidden_layer = derivativeSig(inputHidden)
        first_two_hidden_layer = first_term_hidden_layer * second_term_hidden_layer

        changes = np.dot(outputHidden.T,first_two_output_layer)

        changes_output = np.dot(outputHidden.T,first_two_output_layer)
        changes_output_bias = np.sum(first_two_output_layer,axis = 0,keepdims = True)

        changes_hidden = np.dot(output0.T,first_two_hidden_layer)
        changes_hidden_bias = np.sum(first_two_hidden_layer,axis = 0,keepdims = True)

        wo = wo - lr* changes_output
        bo = bo - lr*changes_output_bias

        wh = wh-lr*changes_hidden
        bh = bh - lr*changes_hidden_bias
output0 = X
inputHidden = np.dot(output0,wh)+bh
outputHidden = sig(inputHidden) 
inputforOutputLayer = np.dot(outputHidden,wo)+bo
output = sig(np.dot(outputHidden, wo) + bo)
output , wh , bh , wo,bo

(array([[  8.16369175e-04],
        [  1.60727143e-02],
        [  1.59950405e-02],
        [  9.76704427e-01]]), array([[ 2.59988015, -3.14210246],
        [ 2.73830571, -3.00957843]]), array([[-3.64347602,  4.29248631]]), array([[ 6.04768657],
        [-6.91613501]]), array([[-0.44114822]]))