In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]]).T # or [[0],[0],[0],[1]]
X.shape,Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [29]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [9]:
# no hidden layer weights
weights = 2*np.random.random((2,1)) - 1# 2 rows 1 col Range -1,1
bias = 2 * np.random.random(1)-1

In [10]:
weights,bias

(array([[-0.43795952],
        [ 0.87363819]]), array([-0.3129994]))

In [12]:
#forward propagation without hidden layer
output0 = X #input layer's  output
output = sig(np.dot(output0,weights)+bias)
output

array([[ 0.42238279],
       [ 0.63660033],
       [ 0.32061239],
       [ 0.53063141]])

In [13]:
## video 2 Forward Prop. 2

In [26]:
wh = 2 * np.random.random((2,2))-1 # 2 , 2 mei jarahe
bh = 2 * np.random.random((1,2))-1 # 1 , 2 mei jaraha hai
wo = 2* np.random.random((2,1)) -1
bo = 2* np.random.random((1,1))-1

In [27]:
output0 = X
outputHidden = sig(np.dot(output0,wh)+bh)
output = sig(np.dot(outputHidden,wo)+bo)

In [28]:
print(output)
outputHidden

[[ 0.62426675]
 [ 0.60749398]
 [ 0.64455798]
 [ 0.63028265]]


array([[ 0.34971099,  0.63272953],
       [ 0.41250957,  0.39756642],
       [ 0.59049023,  0.46878346],
       [ 0.65310179,  0.25263864]])